// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="stream_average,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100tcsg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.263000,HLS_SYN_LAT=32777,HLS_SYN_TPT=32768,HLS_SYN_MEM=4,HLS_SYN_DSP=5,HLS_SYN_FF=921,HLS_SYN_LUT=1105}" *)

module stream_average (
        outstream_TDATA,
        outstream_TLAST,
        instream_TDATA,
        instream_TLAST,
        ap_clk,
        ap_rst_n,
        instream_TVALID,
        instream_TREADY,
        outstream_TVALID,
        outstream_TREADY,
        ap_done,
        ap_start,
        ap_ready,
        ap_idle
);


output  [31:0] outstream_TDATA;
output  [0:0] outstream_TLAST;
input  [31:0] instream_TDATA;
input  [0:0] instream_TLAST;
input   ap_clk;
input   ap_rst_n;
input   instream_TVALID;
output   instream_TREADY;
output   outstream_TVALID;
input   outstream_TREADY;
output   ap_done;
input   ap_start;
output   ap_ready;
output   ap_idle;

wire   [9:0] process_instream_U0_buffer_r_address0;
wire    process_instream_U0_buffer_r_ce0;
wire   [31:0] process_instream_U0_buffer_r_d0;
wire    process_instream_U0_buffer_r_we0;
wire   [9:0] process_instream_U0_buffer_r_address1;
wire    process_instream_U0_buffer_r_ce1;
wire   [31:0] process_instream_U0_buffer_r_d1;
wire    process_instream_U0_buffer_r_we1;
reg    ap_rst_n_inv;
wire    process_instream_U0_buffer_r_full_n;
wire    process_instream_U0_buffer_r_write;
wire    process_instream_U0_instream_TREADY;
wire    process_instream_U0_ap_done;
wire    process_instream_U0_ap_start;
wire    process_instream_U0_ap_ready;
wire    process_instream_U0_ap_idle;
wire    process_instream_U0_ap_continue;
wire    ap_channel_done_buffer;
wire   [31:0] process_outstream_U0_outstream_TDATA;
wire   [0:0] process_outstream_U0_outstream_TLAST;
wire   [9:0] process_outstream_U0_buffer_r_address0;
wire    process_outstream_U0_buffer_r_ce0;
wire   [31:0] process_outstream_U0_buffer_r_d0;
wire    process_outstream_U0_buffer_r_we0;
wire   [9:0] process_outstream_U0_buffer_r_address1;
wire    process_outstream_U0_buffer_r_ce1;
wire   [31:0] process_outstream_U0_buffer_r_d1;
wire    process_outstream_U0_buffer_r_we1;
wire    process_outstream_U0_outstream_TVALID;
wire    process_outstream_U0_buffer_r_read;
wire    process_outstream_U0_ap_done;
wire    process_outstream_U0_ap_start;
wire    process_outstream_U0_ap_ready;
wire    process_outstream_U0_ap_idle;
wire    process_outstream_U0_ap_continue;
wire    ap_sync_continue;
wire   [31:0] buffer_r_i_q0;
wire   [31:0] buffer_r_t_q0;
wire    buffer_r_i_full_n;
wire    buffer_r_t_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire    process_instream_U0_start_full_n;
wire    process_instream_U0_start_write;
wire    process_outstream_U0_start_full_n;
wire    process_outstream_U0_start_write;

process_instream process_instream_U0(
    .instream_TDATA(instream_TDATA),
    .instream_TLAST(instream_TLAST),
    .buffer_r_address0(process_instream_U0_buffer_r_address0),
    .buffer_r_ce0(process_instream_U0_buffer_r_ce0),
    .buffer_r_d0(process_instream_U0_buffer_r_d0),
    .buffer_r_q0(32'd0),
    .buffer_r_we0(process_instream_U0_buffer_r_we0),
    .buffer_r_address1(process_instream_U0_buffer_r_address1),
    .buffer_r_ce1(process_instream_U0_buffer_r_ce1),
    .buffer_r_d1(process_instream_U0_buffer_r_d1),
    .buffer_r_q1(32'd0),
    .buffer_r_we1(process_instream_U0_buffer_r_we1),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .buffer_r_full_n(buffer_r_i_full_n),
    .buffer_r_write(process_instream_U0_buffer_r_write),
    .instream_TVALID(instream_TVALID),
    .instream_TREADY(process_instream_U0_instream_TREADY),
    .ap_done(process_instream_U0_ap_done),
    .ap_start(process_instream_U0_ap_start),
    .ap_ready(process_instream_U0_ap_ready),
    .ap_idle(process_instream_U0_ap_idle),
    .ap_continue(process_instream_U0_ap_continue)
);

process_outstream process_outstream_U0(
    .outstream_TDATA(process_outstream_U0_outstream_TDATA),
    .outstream_TLAST(process_outstream_U0_outstream_TLAST),
    .buffer_r_address0(process_outstream_U0_buffer_r_address0),
    .buffer_r_ce0(process_outstream_U0_buffer_r_ce0),
    .buffer_r_d0(process_outstream_U0_buffer_r_d0),
    .buffer_r_q0(buffer_r_t_q0),
    .buffer_r_we0(process_outstream_U0_buffer_r_we0),
    .buffer_r_address1(process_outstream_U0_buffer_r_address1),
    .buffer_r_ce1(process_outstream_U0_buffer_r_ce1),
    .buffer_r_d1(process_outstream_U0_buffer_r_d1),
    .buffer_r_q1(32'd0),
    .buffer_r_we1(process_outstream_U0_buffer_r_we1),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .outstream_TVALID(process_outstream_U0_outstream_TVALID),
    .outstream_TREADY(outstream_TREADY),
    .buffer_r_empty_n(1'b0),
    .buffer_r_read(process_outstream_U0_buffer_r_read),
    .ap_done(process_outstream_U0_ap_done),
    .ap_start(process_outstream_U0_ap_start),
    .ap_ready(process_outstream_U0_ap_ready),
    .ap_idle(process_outstream_U0_ap_idle),
    .ap_continue(process_outstream_U0_ap_continue)
);

stream_average_bueOg #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
buffer_r_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(process_instream_U0_buffer_r_address0),
    .i_ce0(process_instream_U0_buffer_r_ce0),
    .i_we0(process_instream_U0_buffer_r_we0),
    .i_d0(process_instream_U0_buffer_r_d0),
    .i_q0(buffer_r_i_q0),
    .t_address0(process_outstream_U0_buffer_r_address0),
    .t_ce0(process_outstream_U0_buffer_r_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(buffer_r_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(buffer_r_i_full_n),
    .i_write(process_instream_U0_ap_done),
    .t_empty_n(buffer_r_t_empty_n),
    .t_read(process_outstream_U0_ap_ready)
);

assign ap_channel_done_buffer = process_instream_U0_ap_done;

assign ap_done = process_outstream_U0_ap_done;

assign ap_idle = (process_outstream_U0_ap_idle & process_instream_U0_ap_idle & (buffer_r_t_empty_n ^ 1'b1));

assign ap_ready = process_instream_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = process_outstream_U0_ap_done;

assign ap_sync_ready = process_instream_U0_ap_ready;

assign instream_TREADY = process_instream_U0_instream_TREADY;

assign outstream_TDATA = process_outstream_U0_outstream_TDATA;

assign outstream_TLAST = process_outstream_U0_outstream_TLAST;

assign outstream_TVALID = process_outstream_U0_outstream_TVALID;

assign process_instream_U0_ap_continue = process_instream_U0_buffer_r_full_n;

assign process_instream_U0_ap_start = ap_start;

assign process_instream_U0_buffer_r_full_n = buffer_r_i_full_n;

assign process_instream_U0_start_full_n = 1'b1;

assign process_instream_U0_start_write = 1'b0;

assign process_outstream_U0_ap_continue = 1'b1;

assign process_outstream_U0_ap_start = buffer_r_t_empty_n;

assign process_outstream_U0_start_full_n = 1'b1;

assign process_outstream_U0_start_write = 1'b0;

endmodule //stream_average
