# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Nexys-4-DDR-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_0 || ORIG_REF_NAME==design_1_microblaze_0_0} -quiet] -quiet

# IP: D:/HUST_study/FPGA_based_DSP/nexys_macroblaze_with_mig_with_tft_with_fft/nexys_macroblaze_with_mig_with_tft_with_fft.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_periph_0/design_1_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_1_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: D:/HUST_study/FPGA_based_DSP/nexys_macroblaze_with_mig_with_tft_with_fft/nexys_macroblaze_with_mig_with_tft_with_fft.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_xlconcat_0/design_1_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_xlconcat_0 || ORIG_REF_NAME==design_1_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: ip/design_1_mdm_1_0/design_1_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mdm_1_0 || ORIG_REF_NAME==design_1_mdm_1_0} -quiet] -quiet

# IP: ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_0 || ORIG_REF_NAME==design_1_dlmb_v10_0} -quiet] -quiet

# IP: ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_0 || ORIG_REF_NAME==design_1_ilmb_v10_0} -quiet] -quiet

# IP: ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: D:/HUST_study/FPGA_based_DSP/nexys_macroblaze_with_mig_with_tft_with_fft/nexys_macroblaze_with_mig_with_tft_with_fft.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_0 || ORIG_REF_NAME==design_1_lmb_bram_0} -quiet] -quiet

# IP: ip/design_1_axi_intc_0_0/design_1_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_intc_0_0 || ORIG_REF_NAME==design_1_axi_intc_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mig_7series_0_0 || ORIG_REF_NAME==design_1_mig_7series_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_tft_0_0/design_1_axi_tft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_tft_0_0 || ORIG_REF_NAME==design_1_axi_tft_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xadc_wiz_0_0 || ORIG_REF_NAME==design_1_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xfft_0_2/design_1_xfft_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xfft_0_2 || ORIG_REF_NAME==design_1_xfft_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_datamover_0_1/design_1_axi_datamover_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_datamover_0_1 || ORIG_REF_NAME==design_1_axi_datamover_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_1/design_1_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_1 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_1_1/design_1_axi_smc_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_smc_1_1 || ORIG_REF_NAME==design_1_axi_smc_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_1/design_1_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_1 || ORIG_REF_NAME==design_1_xlconstant_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_2/design_1_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_2 || ORIG_REF_NAME==design_1_xlconstant_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_3/design_1_xlconstant_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_3 || ORIG_REF_NAME==design_1_xlconstant_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_2_0/design_1_axi_smc_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_smc_2_0 || ORIG_REF_NAME==design_1_axi_smc_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_3_1/design_1_axi_smc_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_smc_3_1 || ORIG_REF_NAME==design_1_axi_smc_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_3/design_1_axi_bram_ctrl_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_3 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_2/design_1_axi_bram_ctrl_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_2 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_1/design_1_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_1 || ORIG_REF_NAME==design_1_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_1/design_1_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_1 || ORIG_REF_NAME==design_1_xlslice_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_floating_point_square_imag_0/design_1_floating_point_square_imag_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_square_imag_0 || ORIG_REF_NAME==design_1_floating_point_square_imag_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_floating_point_0_1/design_1_floating_point_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_0_1 || ORIG_REF_NAME==design_1_floating_point_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_floating_point_fix2float_imag_0/design_1_floating_point_fix2float_imag_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_fix2float_imag_0 || ORIG_REF_NAME==design_1_floating_point_fix2float_imag_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dtmv_cmd_0/design_1_dtmv_cmd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dtmv_cmd_0 || ORIG_REF_NAME==design_1_dtmv_cmd_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_floating_point_0_5/design_1_floating_point_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_0_5 || ORIG_REF_NAME==design_1_floating_point_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_floating_point_0_4/design_1_floating_point_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_0_4 || ORIG_REF_NAME==design_1_floating_point_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_floating_point_0_2/design_1_floating_point_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_0_2 || ORIG_REF_NAME==design_1_floating_point_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_floating_point_0_0/design_1_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_0_0 || ORIG_REF_NAME==design_1_floating_point_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_4/design_1_xlconstant_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_4 || ORIG_REF_NAME==design_1_xlconstant_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_datamover_0_0/design_1_axi_datamover_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_datamover_0_0 || ORIG_REF_NAME==design_1_axi_datamover_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_datamover_0_2/design_1_axi_datamover_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_datamover_0_2 || ORIG_REF_NAME==design_1_axi_datamover_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dtmv_mod_mm2s_cmd_0/design_1_dtmv_mod_mm2s_cmd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dtmv_mod_mm2s_cmd_0 || ORIG_REF_NAME==design_1_dtmv_mod_mm2s_cmd_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_smc_0 || ORIG_REF_NAME==design_1_axi_smc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fir_compiler_0_0/design_1_fir_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_0_0 || ORIG_REF_NAME==design_1_fir_compiler_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_hamming_window_0_0/design_1_hamming_window_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_hamming_window_0_0 || ORIG_REF_NAME==design_1_hamming_window_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_5/design_1_xlconstant_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_5 || ORIG_REF_NAME==design_1_xlconstant_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_stream_average_0_0/design_1_stream_average_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_stream_average_0_0 || ORIG_REF_NAME==design_1_stream_average_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_6/design_1_xlconstant_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_6 || ORIG_REF_NAME==design_1_xlconstant_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_mod_read_0/design_1_axi_bram_ctrl_mod_read_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_mod_read_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_mod_read_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_mod_write_0/design_1_axi_bram_ctrl_mod_write_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_mod_write_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_mod_write_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_3/design_1_blk_mem_gen_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_3 || ORIG_REF_NAME==design_1_blk_mem_gen_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_real_0/design_1_xlslice_real_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_real_0 || ORIG_REF_NAME==design_1_xlslice_real_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_floating_point_square_real_0/design_1_floating_point_square_real_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_square_real_0 || ORIG_REF_NAME==design_1_floating_point_square_real_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_imag_0/design_1_xlslice_imag_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_imag_0 || ORIG_REF_NAME==design_1_xlslice_imag_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_floating_point_square_imag_1/design_1_floating_point_square_imag_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_square_imag_1 || ORIG_REF_NAME==design_1_floating_point_square_imag_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_floating_point_fix2float_real_0/design_1_floating_point_fix2float_real_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_fix2float_real_0 || ORIG_REF_NAME==design_1_floating_point_fix2float_real_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dtmv_mod_mm2s_cmd_1/design_1_dtmv_mod_mm2s_cmd_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dtmv_mod_mm2s_cmd_1 || ORIG_REF_NAME==design_1_dtmv_mod_mm2s_cmd_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_floating_point_sqrt_0/design_1_floating_point_sqrt_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_sqrt_0 || ORIG_REF_NAME==design_1_floating_point_sqrt_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_floating_point_float2fix_0/design_1_floating_point_float2fix_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_float2fix_0 || ORIG_REF_NAME==design_1_floating_point_float2fix_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_floating_point_sum_0/design_1_floating_point_sum_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_sum_0 || ORIG_REF_NAME==design_1_floating_point_sum_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_floating_point_fix2float_imag_1/design_1_floating_point_fix2float_imag_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_fix2float_imag_1 || ORIG_REF_NAME==design_1_floating_point_fix2float_imag_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_true_0/design_1_xlconstant_true_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_true_0 || ORIG_REF_NAME==design_1_xlconstant_true_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_datamover_mod_mm2s_0/design_1_axi_datamover_mod_mm2s_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_datamover_mod_mm2s_0 || ORIG_REF_NAME==design_1_axi_datamover_mod_mm2s_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_datamover_mod_s2mm_0/design_1_axi_datamover_mod_s2mm_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_datamover_mod_s2mm_0 || ORIG_REF_NAME==design_1_axi_datamover_mod_s2mm_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dtmv_mod_s2mm_cmd_0/design_1_dtmv_mod_s2mm_cmd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dtmv_mod_s2mm_cmd_0 || ORIG_REF_NAME==design_1_dtmv_mod_s2mm_cmd_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_stream_avg_start_0/design_1_stream_avg_start_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_stream_avg_start_0 || ORIG_REF_NAME==design_1_stream_avg_start_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_stream_average_0_1/design_1_stream_average_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_stream_average_0_1 || ORIG_REF_NAME==design_1_stream_average_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_fft_read_0/design_1_axi_bram_ctrl_fft_read_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_fft_read_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_fft_read_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_fft_write_0/design_1_axi_bram_ctrl_fft_write_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_fft_write_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_fft_write_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_2/design_1_blk_mem_gen_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_2 || ORIG_REF_NAME==design_1_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_1/design_1_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_1 || ORIG_REF_NAME==design_1_xlconcat_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dtmv_fft_cmd_0/design_1_dtmv_fft_cmd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dtmv_fft_cmd_0 || ORIG_REF_NAME==design_1_dtmv_fft_cmd_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xfft_0_0/design_1_xfft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xfft_0_0 || ORIG_REF_NAME==design_1_xfft_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fft_config_0/design_1_fft_config_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fft_config_0 || ORIG_REF_NAME==design_1_fft_config_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_always_true_0/design_1_always_true_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_always_true_0 || ORIG_REF_NAME==design_1_always_true_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fft_all_0_imag_0/design_1_fft_all_0_imag_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fft_all_0_imag_0 || ORIG_REF_NAME==design_1_fft_all_0_imag_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_datamover_fft_0/design_1_axi_datamover_fft_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_datamover_fft_0 || ORIG_REF_NAME==design_1_axi_datamover_fft_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_hamming_ap_start_0/design_1_hamming_ap_start_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_hamming_ap_start_0 || ORIG_REF_NAME==design_1_hamming_ap_start_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_hamming_window_0_1/design_1_hamming_window_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_hamming_window_0_1 || ORIG_REF_NAME==design_1_hamming_window_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fir_compiler_0_1/design_1_fir_compiler_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_0_1 || ORIG_REF_NAME==design_1_fir_compiler_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_1_0/design_1_axi_smc_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_smc_1_0 || ORIG_REF_NAME==design_1_axi_smc_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_2_1/design_1_axi_smc_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_smc_2_1 || ORIG_REF_NAME==design_1_axi_smc_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_3_0/design_1_axi_smc_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_smc_3_0 || ORIG_REF_NAME==design_1_axi_smc_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
