# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/HUST_study/FPGA_based_DSP/microblaze_3_4_1/microblaze_3_4_1.srcs/sources_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xci
# IP: The module: 'design_1_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/HUST_study/FPGA_based_DSP/microblaze_3_4_1/microblaze_3_4_1.srcs/sources_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/HUST_study/FPGA_based_DSP/microblaze_3_4_1/microblaze_3_4_1.srcs/sources_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/HUST_study/FPGA_based_DSP/microblaze_3_4_1/microblaze_3_4_1.srcs/sources_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xci
# IP: The module: 'design_1_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/HUST_study/FPGA_based_DSP/microblaze_3_4_1/microblaze_3_4_1.srcs/sources_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/HUST_study/FPGA_based_DSP/microblaze_3_4_1/microblaze_3_4_1.srcs/sources_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
